version: "3.8"

services:
  morgana:
    build:
      context: .
      target: production
    container_name: morgana
    image: asubowo/morgana:3.0
    restart: unless-stopped
    env_file: .env
    network_mode: bridge
