name: Release Candidate Build Runner

on:
  push:
    branches: [ "rc-*" ]
  pull_request:
    branches: [ "rc-*" ]

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Get version number
      run: |
        VER=$(cat VERSION)
        echo VERSION=$VER >> $GITHUB_ENV

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/morgana:rc-${{ env.VERSION }}
  
    - name: Check if container boots
      run: | 
        docker run --rm ${{ secrets.DOCKER_USERNAME }}/morgana:rc-${{ env.VERSION }} || exit 0

    - name: Check application status
      run: |
        if [ $? -eq 0 ]; then
          echo "Release candidate booted cleanly"
        else
          echo "Release candidate did NOT boot cleanly"
          exit 1
        fi