name: Release Candidate Build Runner

on:
  push:
    branches: [ "rc-*" ]

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Get version number
      run: |
        VER=$(cat VERSION)
        echo VERSION=$VER >> $GITHUB_ENV
        

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/morgana:${{ vars.GITHUB_REF_NAME }}
  
